name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
# Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - 'main'
  tags:
    include:
      - '*'
  paths:
    exclude:
      - docker/jupyterhub
      - docker/spark-py
      - docker/spark-r

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.15
      endpoint: statisticsnorway (6)

    # Pipeline will be run on this base image
pool:
  name: 'extended_storage'

# Variables global to this pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
variables:
  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group: Hemmeligheter
  # Variables defined here
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: imageHost
    value: 'https://eu.gcr.io/'
  - name: imageName
    value: 'eu.gcr.io/prod-bip/ssb/dapla/dapla-jupyterlab'
  - name: repoName
    value: 'prod-bip/ssb/dapla/dapla-jupyterlab'
  - name:  MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  - name: imageTagBeforeVulnerabilityScan
    value: 'imagescan-$(Build.SourceBranchName)-$(Build.SourceVersion)'
  - name: imageTagAfterVulnerabilityScan
    value: '$(Build.SourceBranchName)-$(Build.SourceVersion)'
  - name: imageBuilderLatest
    value: '$(Build.SourceBranchName)-builder-latest'
  - name: imageNotebookLatest
    value: '$(Build.SourceBranchName)-notebook-latest'
  - name: imageTagLatest
    value: '$(Build.SourceBranchName)-latest'
  - name: timeBetweenRetriesVulnerabilityScan
    value: '15000'
  - name: DECODE_PERCENTS
    value: false
  - name: trivyVersion
    value: 0.21.2

jobs:
  - job: pullJavaDependencies
    displayName: 'Pull java dependencies from Maven'
    container: 'maven:3-jdk-11'
    # Job condition: Run these jobs on any branch, but not on tags
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    steps:
      - template: maven/task-authenticate.yml@templates
        parameters:
          connections: 'mvnSsbBipPublic, mvnSsbBipReleases, mvnSsbBipSnapshots'

      - template: maven/task-cache.yml@templates

      - task: Maven@3
        displayName: 'Maven build'
        inputs:
          mavenPomFile: 'build/pom.xml'
          goals: 'clean package'
          options: '-P ssb-bip --batch-mode $(MAVEN_OPTS)'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: false

      # Publish pipeline artifact
      - publish: build/target
        displayName: 'Publish artifact to pipeline'
        artifact: spark-java-libs


  # Job which builds Docker image, pushes this to GCR and checks for any image vulnerabilities
  # NOTE: Sub-project pipelines are still running with the root working directory
  - job: dockerBuildAndDockerPush
    timeoutInMinutes: 150 # how long to run the job before automatically cancelling
    condition: eq(False, startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'Build Docker image for jupyterlab'
    dependsOn: pullJavaDependencies
    steps:
      - script: |
          sudo apt-get install rpm
          wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
          sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
          trivy -v
        displayName: 'Download and install Trivy'
      # Download pipleline artifact
      - download: current
        displayName: 'Download pipeline artifact'
        patterns: '*.jar'
        artifact: spark-java-libs

      # Copy pipeline artifact into working directory
      - bash: |
          cp $(Pipeline.Workspace)/spark-java-libs/*.jar ./docker/jupyterlab
        displayName: 'Copy pipeline artifact into working directory'

      # Authenticate Docker to GCR using predefined service connection
      - task: Docker@2
        displayName: 'Login to GCR'
        inputs:
          command: login
          containerRegistry: gcrServiceConnection

      # Download file with json-key to GCR as a later task needs to
      # authenticate in a different way than using service connection
      # File is stored in Pipelines->Library->Secure Files
      - task: DownloadSecureFile@1
        name: gcrJsonKey
        displayName: 'Download gcr creds'
        inputs:
          secureFile: 'gcr-key.json'

      - script: |
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin ${{ variables.imageHost }}
          docker pull ${{ variables.imageName }}:${{ variables.imageBuilderLatest }}
        displayName: Pull latest for layer caching
        continueOnError: true # for first build, no cache

      # Build Docker build image with cache
      - task: Docker@2
        displayName: 'Build ssb-r-packages'
        inputs:
          repository: ${{ variables.repoName }}
          command: 'build'
          Dockerfile: 'docker/jupyterlab/Dockerfile'
          arguments: '--target ssb-r-packages --cache-from=${{ variables.imageName }}:${{ variables.imageBuilderLatest }}'
          tags: |
            ${{ variables.imageBuilderLatest }}

      # Push Docker build image to GCR
      - task: Docker@2
        displayName: 'Push ssb-r-packages'
        inputs:
          ContainerRegistry: |
            gcrServiceConnection
          repository: ${{ variables.repoName }}
          command: 'push'
          tags: |
            ${{ variables.imageBuilderLatest }}

      - script: |
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin ${{ variables.imageHost }}
          docker images | grep none | awk '{ print $3; }' | xargs docker rmi
        displayName: Remove dangling docker images
        continueOnError: true # for first build, no cache

      - script: |
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin ${{ variables.imageHost }}
          docker pull ${{ variables.imageName }}:${{ variables.imageNotebookLatest }}
        displayName: Pull latest for layer caching
        continueOnError: true # for first build, no cache

      # Build Docker notebook image with cache
      - task: Docker@2
        displayName: 'Build ssb-notebook-image'
        inputs:
          repository: ${{ variables.repoName }}
          command: 'build'
          Dockerfile: 'docker/jupyterlab/Dockerfile'
          arguments: '--target ssb-notebook-image
                      --cache-from=${{ variables.imageName }}:${{ variables.imageBuilderLatest }}
                      --cache-from=${{ variables.imageName }}:${{ variables.imageNotebookLatest }}'
          tags: |
            ${{ variables.imageNotebookLatest }}

      # Push Docker notebook image to GCR
      - task: Docker@2
        displayName: 'Push ssb-notebook-image'
        inputs:
          ContainerRegistry: |
            gcrServiceConnection
          repository: ${{ variables.repoName }}
          command: 'push'
          tags: |
            ${{ variables.imageNotebookLatest }}

      - script: |
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin ${{ variables.imageHost }}
          docker pull ${{ variables.imageName }}:${{ variables.imageTagLatest }}
        displayName: Pull latest for layer caching
        continueOnError: true # for first build, no cache

      - script: |
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin ${{ variables.imageHost }}
          docker images | grep none | awk '{ print $3; }' | xargs docker rmi
        displayName: Remove dangling docker images
        continueOnError: true # for first build, no cache

      # Build Docker final image with cache
      - task: Docker@2
        displayName: 'Build final image'
        inputs:
          repository: ${{ variables.repoName }}
          command: 'build'
          Dockerfile: 'docker/jupyterlab/Dockerfile'
          arguments: '--cache-from=${{ variables.imageName }}:${{ variables.imageBuilderLatest }}
                      --cache-from=${{ variables.imageName }}:${{ variables.imageNotebookLatest }}
                      --cache-from=${{ variables.imageName }}:${{ variables.imageTagLatest }}'
          tags: |
            ${{ variables.imageTagLatest }}
            ${{ variables.imageTagBeforeVulnerabilityScan }}

      # Trivy vulnerability scan, includes python packages installed in image
      - task: CmdLine@2
        displayName: "Trivy vulnerability scan final image"
        inputs:
          script: |
            trivy image --exit-code 0 --severity LOW,MEDIUM ${{ variables.imageName }}:${{ variables.imageTagLatest }}
            trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ variables.imageName }}:${{ variables.imageTagLatest }}

      # Push Docker Image to GCR
      - task: Docker@2
        displayName: 'Push final image'
        inputs:
          ContainerRegistry: |
            gcrServiceConnection
          repository: ${{ variables.repoName }}
          command: 'push'
          tags: |
            ${{ variables.imageTagLatest }}
            ${{ variables.imageTagBeforeVulnerabilityScan }}

      # Set env variable pointing to the file downloaded in previous task
      # as a library in next task needs this env variable
      - script: |
          echo "Setting env variable GOOGLE_APPLICATION_CREDENTIALS"
          echo "##vso[task.setvariable variable=GOOGLE_APPLICATION_CREDENTIALS]$(gcrJsonKey.secureFilePath)"
        displayName: 'Setting GOOGLE_APPLICATION_CREDENTIALS env variable'

      # Wait for scan on image in GCR to complete and check for any vulnerabilities
      # with effective severity HIGH or CRITICAL
      - task: gcr-vulneralbility-check@0
        displayName: 'Image vulnerability check'
        inputs:
          projectId: 'prod-bip'
          imageHost: ${{ variables.imageHost }}
          image: ${{ variables.repoName }}
          imageTag: ${{ variables.imageTagBeforeVulnerabilityScan }}
          timeBetweenRetries: ${{ variables.timeBetweenRetriesVulnerabilityScan }}

      - script: |
          TAG=`git describe --tags`
          echo $TAG
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin ${{ variables.imageHost }}
          docker pull ${{ variables.imageName }}:${{ variables.imageTagBeforeVulnerabilityScan }}
          docker tag ${{ variables.imageName }}:${{ variables.imageTagBeforeVulnerabilityScan }} ${{ variables.imageName }}:${{ variables.imageTagAfterVulnerabilityScan }}
          docker push ${{ variables.imageName }}:${{ variables.imageTagAfterVulnerabilityScan }}
        displayName: "Retagging docker image if successful vulnerability scan"
        condition: succeeded()

      # Need to tag 'latest' image (used by docker-tag-for-production)
      - script: |
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin ${{ variables.imageHost }}
          docker pull ${{ variables.imageName }}:${{ variables.imageTagAfterVulnerabilityScan }}
          docker tag ${{ variables.imageName }}:${{ variables.imageTagAfterVulnerabilityScan }} ${{ variables.imageName }}:latest
          docker push ${{ variables.imageName }}:latest
        displayName: "Retagging latest image"
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))


  # Job which pulls the Docker image with the 'latest' tag from GCR, tags this
  # with the git tag, and pushes that back to GCR.
  # The job triggers when any tag was committed to GitHub, which means all tags in
  # the code repo are propagated to the corresponding (newly built) image in GCR.
  - template: docker/docker-tag-for-production.yml@templates
    parameters:
      tagToTag: 'latest'
      gcrImageName: ${{ variables.imageName }}
